version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t russ-ssm-env:latest .
      - docker tag russ-ssm-env:latest 480810688838.dkr.ecr.us-east-2.amazonaws.com/russ-ssm-env:latest
  post_build:
    commands:
      - echo Build completed on `date`